### ISSUE TITLE
Exceptions app unexpectedly looks for a layout even when the request is a json request

### ISSUE THREAD

**Issue by yuki24** [yuki24/rambulance#13]
It shouldn't look for any layout templates.

![screen shot 2015-01-06 at 8 19 30 am](https://cloud.githubusercontent.com/assets/386234/5629042/fc7f3d12-957c-11e4-9cdc-d3f0f63329cd.png)

**Comment by gingerlime** [comment]
Was this resolved?

I noticed a similar issue when making JSON requests and it ended up raising a `MissingTemplate` error from the rambulance exception app. I see that there's a development dependency on `jbuilder`, but not for production. The json templates use `jbuilder`, so anyone who doesn't have the gem already installed and uses the generator might bump into a similar issue. I wonder if it makes sense to add `jbuilder` as a dependency not just for development?

**Comment by yuki24** [comment]
@gingerlime this issue is still there :(

The reason why jbuilder is not a runtime dependency is that someone can still other templates like [rabl](https://github.com/nesquena/rabl) and remove default jbuilder templates. But I think at least a helpful error message should be provided if jbuilder is missing.

**Comment by gingerlime** [comment]
Yeah, it makes sense. I was just wondering if the generator should automatically generate those `jbuilder` files, even when the rails app might not have `jbuilder` installed, or it uses something else?
