### ISSUE TITLE
Best way to dynamically render the error message

### ISSUE THREAD

**Issue by take** [yuki24/rambulance#15]
So if I'm correct, rambulance catches any rack exceptions and executes the action method defined in ExceptionsApp(e.g. ExceptionsApp#not_found).

And I wanted to render the error mesage raised in the rack so I did it by editing the view file as below

```
json.error_message @_request.env['action_dispatch.exception'].try(:message) || "DEFAULT ERROR MESSAGE"
```

But since I don't know much about rack middlewares, I'm not sure if this is the ideal way.
Are there any other better solutions?

**Comment by yuki24** [comment]
That's what I usually do.

**Comment by take** [comment]
aha ok thanks :)

**Comment by take** [comment]
@yuki24 wdyt about adding a view helper for this?

**Comment by yuki24** [comment]
@take they have been added: d0beb85fd92a7bd60dac214b07c8a421265af0c2

**Comment by take** [comment]
@yuki24 woot thanks!

**Comment by yuki24** [comment]
will cut a new version soon. Thanks!

**Comment by take** [comment]
thanks! :bow:
