### ISSUE TITLE
Any way to suppress Rails FATAL logging when handled by rambulance? 

### ISSUE THREAD

**Issue by gingerlime** [yuki24/rambulance#16]
Hi @yuki24,

Thanks for creating this gem. I'm testing it out, and it looks really nice and seems to work well.

My question is with the following example / scenario:

The following curl command:
`curl -D - -X PUT --data "not json" -H "Content-Type: application/json" http://localhost:3000`

would generate a `ActionDispatch::ParamsParser::ParseError`.

When I configure rambulance like this, it works great and returns a 400 as expected.
```ruby
config.rescue_responses = {
  'ActionDispatch::ParamsParser::ParseError' => :bad_request,
  ...
}
```

So far so good. One thing that I noticed however, even when requests are caught and handled correctly by rambulance, rails still logs a `FATAL` message, which gets emailed automatically on production. It's great to get an email for something that wasn't handled, but when it *is* handled by rambulance, then I wonder if there's a way to suppress this error from being logged and prevent an email from being sent out?

(I know it's probably not strictly an issue with rambulance, but I would appreciate your help / thoughts about this)

**Comment by yuki24** [comment]
glad you liked this gem!

Are you using `exception_notification` or Airbrake or something else? I would actually say just ignore them. I know it's annoying, but it happens even if you don't use rambulance. Also, this could be related: https://github.com/rails/rails/issues/17731

**Comment by gingerlime** [comment]
Hi @yuki24 

Thanks for getting back to me. We're using [logging-rails](https://github.com/TwP/logging-rails), which has an email adapter. It works really well for us. But I'm not sure if we can easily silence individual messages with this gem. I think it's globally set based on the logging level... 

I know it's not specific to `rambulance`, but was just wondering about the best strategy. Thanks for the link. It seems useful, but not sure it fits our particular case.

One more thing worth asking your opinion about (and again, I know it's not specific to `rambulance`, but as a general approach). What worked quite well for us in those bot attack cases, is [rack-robusness](https://github.com/blambeau/rack-robustness). This allows us to block specific exception inside Rack itself, without pointing them back into the exceptions app / rambulance. The downside to this approach is that we can't (easily) tweak the templates that get returned to the user. So that makes it more suitable for blocking things that we're 100% sure are plain bots... Wondering about your opinion about this approach / mixing it with rambulance ?

**Comment by yuki24** [comment]
Have you tried [rack-attack](https://github.com/kickstarter/rack-attack)? If you already know they are bots, then you should be able to block them with the gem.

**Comment by gingerlime** [comment]
Yes, thanks. I'm familiar with it. Even [recommended](http://stackoverflow.com/a/25487047/305019) it as one of the options to deal with this `alihack` hack ;-) But I have some reservations with using it, because it's very specific to a narrow blacklist (typically IP, or more exact request pattern). Ideally, I'd like to deal with any `ActionDispatch::ParamsParser::ParseError` in the more general sense, i.e. log it as warning (not `FATAL`) and return a reasonable template with a 400 response.

rambulance solves the last part well, but I'm wondering about the best strategy to dealing with the first part (logging / suppressing some logs)

**Comment by gingerlime** [comment]
@yuki24 - as a followup to my question. I managed to suppress the `FATAL` errors by rails by using the filter functionality of the `logging` gem.

However, I'm curious if there's a way to catch some trivial errors (like `ActiveRecord::RecordNotFound`), and "plug" them into rambulance from within rails? i.e. instead of throwing them up to Rack, and then back again - just do something like this in my application controller

```ruby
rescue_from ActiveRecord::RecordNotFound, :with => :not_found

def not_found
  ExceptionsApp.not_found
end
```

I tried various things like `ExceptionsApp.action(:not_found).call(request.env)`, but somehow it doesn't work and I'm not entirely sure what's the reason. Maybe because the exception is not appended to the env?

Hope my question / request makes sense, but happy to explain in more detail if necessary

**Comment by yuki24** [comment]
You should never use `rescue_from` to render error pages.

Also, what's stopping you from switching to airbrake or exception_notification or something like that? I don't think using logging-rails for error reporting is ideal. Airbrake, honeybadger, and exception_notification all allow you to configure exceptions you want to ignore with a few lines of code.

To me it seems like logging-rails just introduces issues that shouldn't exist. It's an indicator of a bad pattern and you should avoid doing that.

**Comment by yuki24** [comment]
And again, rambulance never writes anything to any logger. Rails does it by design. If you want to ignore a particular exception from what logging-rails reports, it should be configurable through logging-rails, not rambulance.

**Comment by gingerlime** [comment]
Thanks for your patience. I think I didn't explain myself properly. I'm sorry.

First of all, I totally understand it's not something from within rambulance, but I'm asking for your advice since you're familiar with the whole exception handling in rails. It's more to do with how rails "plugs" the exception app and how it might affect other things on the middleware stack.

`logging-rails` can definitely filter exceptions very easily, and that's what we're doing right now.

My question / problem is somewhere between an optimization issue and how other middleware / gems might get "confused" when it comes to handling all exceptions by throwing them up to be handled by the exceptions app. I'll try to explain

When the request 'leaves' your app and travels up the middleware stack, it's in an exception state. So Rails logs it as a `FATAL` error, and other gems might log / treat it as an error as well (I saw this with, e.g. the [`lograge` gem](https://github.com/roidrage/lograge)). I can and already do suppress the Rails `FATAL` exception, but now I noticed that `lograge` logs the request twice - once as a 500, and another time as 404.

This is a consideration for any exceptions app, not just rambulance. I'm just wondering if some errors should be treated from within the app first, and only as a safeguard via the exceptions app? This could reduce the processing time up the middleware stack, and avoid "confusing" some gems...

Hope I managed to explain myself better this time. But happy to clarify if necessary. I would greatly appreciate your feedback on this.

**Comment by gingerlime** [comment]
I created a sample app that demonstrates the issue I see with `lograge`, see https://github.com/gingerlime/rambulance-example-app

If you make a request to `/` it raises an `ActiveRecrord::RecordNotFound` exception. This gets caught by rambulance and the user sees a 404. No problem there. However, `lograge` in this case logs two requests. One with the status of 500, and another 404.

```
=> Booting WEBrick
=> Rails 4.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-03-29 08:03:36] INFO  WEBrick 1.3.1
[2015-03-29 08:03:36] INFO  ruby 2.2.0 (2014-12-25) [x86_64-linux]
[2015-03-29 08:03:36] INFO  WEBrick::HTTPServer#start: pid=26368 port=3000

method=GET path=/ format=*/* controller=application action=index status=500 error='ActiveRecord::RecordNotFound:ActiveRecord::RecordNotFound' duration=9.40

ActiveRecord::RecordNotFound (ActiveRecord::RecordNotFound):
  app/controllers/application_controller.rb:7:in `index'


method=GET path=/404 format=*/* controller=application action=index status=404 duration=65.13 view=62.10 db=0.00
```

Again - rambulance is not the source of the problem here. It could very well be that `lograge` doesn't handle things properly, but I think this can also confuse other gems that plug into rack...

**Comment by dnajd** [comment]
@gingerlime how did you get rid of that additional log noise.  I'm trying to get it out of my log files as well; using lograge.  Thanks!

**Comment by gingerlime** [comment]
Hey @dnajd, I ended up using this snippet for lograge to reduce noise. It feels a bit hacky, but seems to work

```ruby
# config/environments/production.rb
  config.lograge.ignore_custom = lambda do |event|
    # the ExceptionsApp (Rambulance) handles all errors. Errors raised by other
    # controllers can be ignored by lograge until they reach the exceptions app.
    payload = event.payload
    if payload[:exception].present? && payload[:controller] != 'ExceptionsApp'
      return true
    end
    false
  end
```

I still think it would be better if rambulance hooked both into the middleware stack (for exceptions outside the rails app), and around rails itself (e.g. rescue from application controller). It will save unnecessary roundtrips through the middleware stack for local errors and play nicely with any other middleware that assumes errors are handled by the application rather than "let loose". Unfortunately I don't think I have the rails chops to figure out how to make this happen (or the time to dig into this).

Hope my workaround is helpful though, at least for lograge.

**Comment by dnajd** [comment]
@gingerlime thank you so much for the reply.  I put that into my environment.rb to test locally and I still get errors like this in my log files

```
NameError (undefined local variable or method `asdfds' for #<WelcomeController:0x007fcbe5c27b68>):
  app/controllers/welcome_controller.rb:3:in `index'
```

In this example I have put the classic "asdf" into my welcome controller to cause an error and it gives me this unformatted name error in my log file. :(

**Comment by gingerlime** [comment]
Did you test this with `consider_all_requests_local = false` on your dev environment?

However, I think some stuff gets logged by one of the rails middleware and there's not much you can do about that. I also use `logging-rails` gem and added a filter there, so at least we don't get emailed about this error. I think you can filter it out completely there if you want. It's really far from perfect, and that's why I hope rambulance (or something else?) can also hook somewhere inside the app... As I said, it's kinda out of my league though.

**Comment by gingerlime** [comment]
for reference, here's the filter I created for the email appender of `logging-rails`:

```ruby
# filters all logging events that are logged by 'Rails'
class FilterRailsLogger < ::Logging::Filter
  def allow(event)
    # if the event logger is `Rails`, we filter the event
    event.logger == 'Rails' ? nil : event
  end
end

# ...
Logging::Rails.configure do |config|
  # ...
  Logging.appenders.email( 'email',
    :from     => #...
    :to       => # ...
    # ...
    # Filtering Rails logs to avoid unneccessary emails.
    :filters => [FilterRailsLogger.new]
  ) if config.log_to.include? 'email'
  # ...
end
```

**Comment by dnajd** [comment]
I found a solution to keep my lograge logs clean... If you configure it to keep the original rails logs, then the unformatted messages go there instead.

```
config.lograge.keep_original_rails_log = true
config.lograge.logger = ActiveSupport::Logger.new "#{Rails.root}/log/lograge_#{Rails.env}.log"
config.lograge.enabled = true
```

With this setup the fatal message (not formatted)
```
NameError (undefined local variable or method `asdfds' for #<WelcomeController:0x007fcbe5c27b68>):
  app/controllers/welcome_controller.rb:3:in `index'
```

goes into the rails log and lograge log includes only the well formatted message
```
2015-06-10T08:42:13-07:00 app="rails_loaded"|method="GET"|path="/"|format="html"|controller="WelcomeController"|action="index"|status="500"|duration="3.57"|view="0.0"|db="0.0"|error="NameError: undefined local variable or method `zsd' for #<WelcomeController:0x007fecf95dfc80>"
```

I'm sort of happy. lol
