### ISSUE TITLE
generator only generate jbuilder template

### ISSUE THREAD

**Issue by mkhairi** [yuki24/rambulance#24]
when i try run 'rails g rambulance:install' only jbuilder template was generated. same goes to 'rails g rambulance:install -e slim'

**Comment by yuki24** [comment]
@mkhairi what behaviour would you expect instead?

**Comment by mkhairi** [comment]
@yuki24 should it be also 
generate erb file right? or i missed something new here?

**Comment by yuki24** [comment]
@mkhairi it should generate erb templates. Could you post your Gemfile here?

**Comment by mkhairi** [comment]
@yuki24, i using gem 'slim-rails'. Maybe rambulance 0.3.0(published rubygems) generator is not support slim yet. When i run 'rails g rambulance:install' erb is not use by default and maybe generator detect default template is slim.
I test with master branch right now and everything is working well.  Waiting for next release. Thanks! :)

**Comment by yuki24** [comment]
@mkhairi seems like I should cut a new version. Thanks!
