### ISSUE TITLE
Ability to create static 500.html on deploy

### ISSUE THREAD

**Issue by freaz** [yuki24/rambulance#35]
Is there a way how to create  static version of `internal_server_error` action?

For example as step in Capistrano deploy:

```ruby
task :generate_500_html do
  on roles(:web) do |host|
    # generate 500.html
  end
end
after "deploy:published", :generate_500_html
```

**Comment by yuki24** [comment]
I wouldn't recommend auto-generating error pages based on what the controller renders. Instead, consider using haml to generate statis error pages: http://devoh.com/blog/2012/09/asset-pipeline-error-pages
This is a much simpler solution that allows you to share all the assets in your app across the main app and the error pages.
