### ISSUE TITLE
Rambulence causes "Error during failsafe response" when POST body is malformed

### ISSUE THREAD

**Issue by jasim** [yuki24/rambulance#40]
Rails raises `Rack::QueryParser::InvalidParameterError` exception on receiving a malformed POST body, which under usual circumstances results in a 400 Bad Request response.

But Rambulance intercepts this error and turns it into a 500 Internal Server error. 

    Error during failsafe response: Invalid request parameters: invalid %-encoding (abcd%%72900)

This is demonstrated in https://github.com/jasim/rambulance_error_in_failsafe_response

To reproduce, start the above server and send a POST request with the following unparseable data:

    rails server

    curl -D - --request POST \
      --url http://localhost:3000/test \
      --header 'content-type: application/x-www-form-urlencoded' \
      --data email=abcd%%72900

This produces:

    HTTP/1.1 500 Internal Server Error
    Content-Type: text/plain
    ..
    ..

    500 Internal Server Error
    If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

But the correct response should have been:

    HTTP/1.1 400 Bad Request
    Content-Type: text/html; charset=UTF-8
    Content-Length: 0
    ..
    ..
## Details

Rails raises `Rack::QueryParser::InvalidParameterError` exception on receiving the malformed POST body, which under usual circumstances results in a 400 Bad Request response.

But when Rambulance intercepts this error, it tries to render it through its `ExceptionsApp` controller. This means the request goes through `ActionDispatch::Request` again, which in turn calls `Rack::QueryParser`, and ends up in the "Error during failsafe response" exception. This swallows the original 400 Bad Request, and the response becomes a 500 Internal Server Error instead.

**Comment by yuki24** [comment]
Thanks for reporting and taking your time on writing an example app. I'll look into it.

**Comment by jasim** [comment]
Thanks for the quick response and for writing Rambulance! Please let us know if there is anything we can do to help resolve this. (cc-ing @gingerlime)

**Comment by yuki24** [comment]
My pleasure! If you are using Rails 5.0 or newer, would you mind trying the `fix-malformed-body-error` branch?

```ruby
gem 'rambulance', git: 'https://github.com/yuki24/rambulance.git', ref: 'fix-malformed-body-error'
```

**Comment by jasim** [comment]
It works! I get a 400 Bad Request, and bad_request.html.erb is rendered as well.

**Comment by gingerlime** [comment]
it's a bit late, so sorry if I'm wrong, because I didn't have a chance to play around with it yet... I think the same problem could also happen with any malformed GET param though as well (and I assume any other HTTP verb?).

**Comment by yuki24** [comment]
That's a good point. We already have a guard against malformed query strings ([test cases can be found here](https://github.com/yuki24/rambulance/blob/master/test/requests/error_page_test.rb#L28-L42)) and GET requests are not allowed to be sent with body (at least by specification). We may still need to check other verbs as well, most importantly PATCH and PUT. It's also worth reporting to upstream Rails.

Thanks @jasim @gingerlime again for reporting!

**Comment by gingerlime** [comment]
Thanks a lot @yuki24 !

> ... and GET requests are not allowed to be sent with body (at least by specification)

Well, that's part of the problem. These are malicious requests in most cases. So this kind of request might also fail, despite the checks for GET params if I'm not mistaken

`curl -X GET -D - --data email=abcd%%72900 http://localhost:3000`

**Comment by yuki24** [comment]
Now the `ExceptionsApp` sanitizes both the query string and request body regardless of HTTP verbs, so this should fix this issue for not just get requests but for any requests.

**Comment by gingerlime** [comment]
Thanks @yuki24 ! seems to do the trick :) Are you planning to publish a new rambulance version?

**Comment by yuki24** [comment]
I'll give it a few more days to make sure it's stable enough and cut a new release afterwards.

**Comment by yuki24** [comment]
Happy new year, @gingerlime @jasim! I just cut a new release [0.5.0](https://rubygems.org/gems/rambulance/versions/0.5.0) with fixes for this bug. Thanks!

**Comment by gingerlime** [comment]
That's great to hear, @yuki24! Happy 2018 to you too.
