### ISSUE TITLE
Drop of haml tamplate

### ISSUE THREAD

**Issue by joker-777** [yuki24/rambulance#43]
Hi,

we saw in your changelog that you dropped the support of haml templates but somehow our haml templates still work. Any idea why? Do we have to worry that they won't work in future?

Thanks!

**Comment by yuki24** [comment]
I guess I should have been more clear on that - what actually has been dropped was generate haml templates with the `rails g ...` command. Your haml templates should still work fine, and I’m not going to drop that. I’ll update the README tomorrow. Thanks!

**Comment by yuki24** [comment]
fixed by 2d7a55e633d583353fffb7680c5670907e52796f

**Comment by joker-777** [comment]
Thanks for clarifying!!!
