### ISSUE TITLE
Depreacte Custom Exceptions App

### ISSUE THREAD

**Issue by yuki24** [yuki24/rambulance#47]
Custom Exceptions App isn't worth given the risks in it.

**Comment by adrianhuna** [comment]
I am using custom exceptions app to setup stuff like localization and force no caching (had issues with error page not being rendered in the correct language). 

Could you advise how to solve it without custom ExceptionsApp? 

Example for the no cache:

```
class MyExceptionsApp < ::Rambulance::ExceptionsApp
  before_action -> { expires_now }
end
```

**Comment by yuki24** [comment]
That seems like a legit use case. I wonder if there is any other way to invalidate cache without having to create your own exceptions app, but it does sound like we can't deprecate it unless we find a good solution.
