### ISSUE TITLE
Setting Flash and redirecting in Custom Exceptions App not working

### ISSUE THREAD

**Issue by bb** [yuki24/rambulance#69]
The Readme mentions I can set a `flash[:notice]` in a [Custom Exceptions App](https://github.com/yuki24/rambulance#custom-exceptions-app). This is true when rendering a response page directly from the ExceptionsApp. However, it does not work when redirecting directly from the action in the Exceptions App. The redirect itself works fine.

I tried both `flash[:notice] = "something"` and `redirect_to new_user_session_path, notice: "something"`.

Ideally, I think setting a flash and redirecting should work as it does outside the Exceptions App. If it's not expected to be working, the Readme should be clarified.

**Comment by yuki24** [comment]
Are you trying to call `redirect_to new_user_session_path, notice: "something"` from within the exceptions app? That may not work as you expect as it never hits the `ActionDispatch::Flash` middleware. It's also probably impossible to support it as it may require some dangerous hacks (any hack in the exceptions app is risky).

**Comment by yuki24** [comment]
As you pointed out, the example in the README with `flash` is probably misleading. That should be updated for sure.

**Comment by bb** [comment]
Yes, that’s exactly what I tried.

I think we should clarify in the ReadMe that flash is only working if you render within the exception app, not when redirecting to the main app. Current wording sounds to me like both would work:

> You can use whatever techniques you want to use in controllers like before_filter and flash[:notice] = "message..." …

**Comment by bb** [comment]
I saw your second comment just now. Should I create a PR?

**Comment by yuki24** [comment]
> I saw your second comment just now. Should I create a PR?

Yeah that would be fantastic. Thanks in advance!

**Comment by bb** [comment]
See #71. I considered being more generic about what works and what not but as I do not fully understand every aspect, I kept it very close to what we discussed here. Feel free to edit it.

**Comment by yuki24** [comment]
@bb I just merged it. Thank you!
