### ISSUE TITLE
Rack changed 422 from "unprocessable_entity" to "unprocessable_content"

### ISSUE THREAD

**Issue by tmaier** [yuki24/rambulance#77]
`Rack::Utils::SYMBOL_TO_STATUS_CODE` does not know about `unprocessable_entity` any more.

This should impact

https://github.com/yuki24/rambulance/blob/5492a723280e7b5d7cb19df50b4c432428244500/lib/rambulance/exceptions_app.rb#L4-L10
Will not generate an action for `unprocessable_entity`, which will continue to be used in Rails 7 for the time being.

https://github.com/yuki24/rambulance/blob/5492a723280e7b5d7cb19df50b4c432428244500/lib/rambulance/exceptions_app.rb#L37
Returns `nil` for `unprocessable_entity`.

Related issues at https://github.com/rails/rails/pull/52087 and https://github.com/rspec/rspec-rails/issues/2763

**Comment by yuki24** [comment]
Thanks for reporting! This is quite a big change, I will look to see if we can display deprecation warnings, etc.

**Comment by yuki24** [comment]
Indeed, the latest build for c383e5ad25401c0a7f1158b58d34799f9f75f3e2 is breaking: https://github.com/yuki24/rambulance/actions/runs/10232953081

#78 should address that, and I will cut a new release as soon as we have ✅

**Comment by yuki24** [comment]
Cut a new release as [3.2.0](https://rubygems.org/gems/rambulance/versions/3.2.0). Thanks!

**Comment by tmaier** [comment]
Thank you! I believe it makes sense to improve the CHANGELOG entry. 

When i understand #78 correctly, one would need to rename `app/views/errors/unprocessable_entity.html.erb` to `app/views/errors/unprocessable_content.html.erb` to stay compabtible with 3.2

And one should update the hash values of `config.action_dispatch.rescue_responses`  to `unprocessable_content`.

**Comment by yuki24** [comment]
Ah, I guess redirection does not seem like a good idea as it may be a breaking change. We could have totally kept both `unprocessable_entity` and `unprocessable_content` and start a gradual migration process with a guide in the README. That said, the release is already there, so there is no going back unfortunately (we could yank, but I generally do that only for security incidents).

@tmaier Would you mind sending a PR for updating the CHANGELOG?
